#!/usr/bin/expect

if {$argc != 5 } {
   puts stderr "Usage: ip user passwd localfile remote_path"
   exit
}
set host_ip [lindex $argv 0]
set user [lindex $argv 1]
set passwd [lindex $argv 2]
set filename [lindex $argv 3]
set remote_path [lindex $argv 4]

spawn scp -P60086 $filename $user@$host_ip:$remote_path

expect {
    "(yes/no)?" { send "yes\r"; exp_continue} 
    "*password:" {  send "$passwd\r"; } 
}

expect "100\%"

expect eof
exit 
