#!/usr/bin/expect

if {$argc != 4} {
   puts stdout "Usage: ip user passwd cmd"
   exit
}

set host_ip [lindex $argv 0]
set user [lindex $argv 1]
set passwd [lindex $argv 2]
set cmd [lindex $argv 3]

spawn ssh -p60086 $user@$host_ip

puts stdout "cmd: $cmd"
expect {
    "(yes/no):" { send "yes\r"; exp_continue} 
    "*password:" { send "$passwd\r"; } 
}

expect "~]" 
send "$cmd \r";

expect "~]"
send "exit\r"

expect eof
exit
